export default [
  {
    type: 'constructor',
    inputs: [
      { name: 'factory_', type: 'address', internalType: 'address' },
      { name: 'weth_', type: 'address', internalType: 'address' },
      { name: 'universalRouter_', type: 'address', internalType: 'address' },
      { name: 'permit2_', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'factory',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IClanker' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'permit2',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IPermit2' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'receiveTokens',
    inputs: [
      {
        name: 'deploymentConfig',
        type: 'tuple',
        internalType: 'struct IClanker.DeploymentConfig',
        components: [
          {
            name: 'tokenConfig',
            type: 'tuple',
            internalType: 'struct IClanker.TokenConfig',
            components: [
              { name: 'tokenAdmin', type: 'address', internalType: 'address' },
              { name: 'name', type: 'string', internalType: 'string' },
              { name: 'symbol', type: 'string', internalType: 'string' },
              { name: 'salt', type: 'bytes32', internalType: 'bytes32' },
              { name: 'image', type: 'string', internalType: 'string' },
              { name: 'metadata', type: 'string', internalType: 'string' },
              { name: 'context', type: 'string', internalType: 'string' },
              { name: 'originatingChainId', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'poolConfig',
            type: 'tuple',
            internalType: 'struct IClanker.PoolConfig',
            components: [
              { name: 'hook', type: 'address', internalType: 'address' },
              { name: 'pairedToken', type: 'address', internalType: 'address' },
              { name: 'tickIfToken0IsClanker', type: 'int24', internalType: 'int24' },
              { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
              { name: 'poolData', type: 'bytes', internalType: 'bytes' },
            ],
          },
          {
            name: 'lockerConfig',
            type: 'tuple',
            internalType: 'struct IClanker.LockerConfig',
            components: [
              { name: 'locker', type: 'address', internalType: 'address' },
              { name: 'rewardAdmins', type: 'address[]', internalType: 'address[]' },
              { name: 'rewardRecipients', type: 'address[]', internalType: 'address[]' },
              { name: 'rewardBps', type: 'uint16[]', internalType: 'uint16[]' },
              { name: 'tickLower', type: 'int24[]', internalType: 'int24[]' },
              { name: 'tickUpper', type: 'int24[]', internalType: 'int24[]' },
              { name: 'positionBps', type: 'uint16[]', internalType: 'uint16[]' },
              { name: 'lockerData', type: 'bytes', internalType: 'bytes' },
            ],
          },
          {
            name: 'mevModuleConfig',
            type: 'tuple',
            internalType: 'struct IClanker.MevModuleConfig',
            components: [
              { name: 'mevModule', type: 'address', internalType: 'address' },
              { name: 'mevModuleData', type: 'bytes', internalType: 'bytes' },
            ],
          },
          {
            name: 'extensionConfigs',
            type: 'tuple[]',
            internalType: 'struct IClanker.ExtensionConfig[]',
            components: [
              { name: 'extension', type: 'address', internalType: 'address' },
              { name: 'msgValue', type: 'uint256', internalType: 'uint256' },
              { name: 'extensionBps', type: 'uint16', internalType: 'uint16' },
              { name: 'extensionData', type: 'bytes', internalType: 'bytes' },
            ],
          },
        ],
      },
      {
        name: 'tokenPoolKey',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'extensionSupply', type: 'uint256', internalType: 'uint256' },
      { name: 'extensionIndex', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'universalRouter',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUniversalRouter' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'weth',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IWETH9' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'EthDevBuy',
    inputs: [
      { name: 'token', type: 'address', indexed: true, internalType: 'address' },
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      { name: 'ethAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'tokenAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'InvalidEthDevBuyPercentage', inputs: [] },
  { type: 'error', name: 'InvalidMsgValue', inputs: [] },
  { type: 'error', name: 'InvalidPairedTokenPoolKey', inputs: [] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  { type: 'error', name: 'Unauthorized', inputs: [] },
] as const
